apiVersion: v2
name: ddn-workspace
description: A Helm chart for DDN Workspace (Native Runtime)
type: application
version: v2025.12.01
appVersion: "3.0.0"
dependencies:
- name: common
  version: 0.0.16
  repository: oci://us-west1-docker.pkg.dev/hasura-ee/helm-charts
