{{- if and (include "ddn-workspace.workspaceAuthProxy.enabled" .) .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common.name" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    component: workspace-auth-proxy
  annotations:
    {{- if .Values.global.certIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.global.certIssuer }}
    {{- end }}
    {{- if .Values.ingress.ingressClassName }}
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClassName }}
    {{- end }}
    {{- if not .Values.global.subDomain }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  tls:
  - hosts:
    {{- if .Values.global.subDomain }}
    - {{ include "ddn-workspace.domain" . }}
    {{- else }}
    - {{ .Values.global.domain }}
    {{- end }}
    secretName: {{ include "ddn-workspace.workspaceAuthProxy.name" . }}-tls
  rules:
  {{- if .Values.global.subDomain }}
  - host: {{ include "ddn-workspace.domain" . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "common.name" . }}
            port:
              number: {{ .Values.workspaceAuthProxy.service.port }}
  {{- else }}
  - host: {{ .Values.global.domain }}
    http:
      paths:
      - path: /{{ include "common.name" . }}(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "common.name" . }}
            port:
              number: {{ .Values.workspaceAuthProxy.service.port }}
  {{- end }}
{{- end }}
