# ingress.yaml - Use common ingress template with conditional servicePort
{{- $_ := set .Values.ingress "servicePort" (include "ddn-workspace.ingress.servicePort" .) -}}
{{- template "common.ingress" . -}}
